name: SWxSOC Workflows

on:
  pull_request:
    branches:
      - main

jobs:
  # Workflow to run test calibration using mock Lambda function test_data/test_<instrument>_event.json event
  # https://github.com/HERMES-SOC/.github/blob/main/workflows/calibration.yml
  calibration-workflow:
    permissions:
      pull-requests: write
    uses: HERMES-SOC/.github/blob/main/workflows/calibration.yml
  
  # Workflow to run linting on the codebase
  # https://github.com/HERMES-SOC/.github/blob/main/workflows/codestyle.yml
  linting-workflow:
    uses: HERMES-SOC/.github/blob/main/workflows/codestyle.yml

  # Workflow to build the documentation
  # https://github.com/HERMES-SOC/.github/blob/main/workflows/docs.yml
  docs-workflow:
    uses: HERMES-SOC/.github/blob/main/workflows/docs.yml
  
  # Workflow to run the test suite
  # https://github.com/HERMES-SOC/.github/blob/main/workflows/testing.yml
  testing-workflow:
    uses: HERMES-SOC/.github/blob/main/workflows/testing.yml