# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CDF_LIB
jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test]
    - name: Run tests
      shell: cmd
      run: |
      curl -L "https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/latest/windows/cdf3.9.0_64bit_WinZip_Installer.zip" --output cdf.zip
      mkdir cdf_lib
      tar -xf cdf.zip -C cdf_lib  
      set mydir=%cd%
      set CDF_BASE=%mydir%\cdf_lib
      set CDF_INC=%mydir%\cdf_lib\include
      set CDF_LIB=%mydir%\cdf_lib\lib
      set CDF_HELP=%mydir%\cdf_lib\help
      set CDF_LEAPSECONDSTABLE=%mydir%\cdf_lib\CDFLeapSeconds.txt
      set CLASSPATH=%mydir%\cdf_lib\CDFToolsDriver.jar;%mydir%\cdf_lib\lib\cdfjava.jar;%mydir%\cdf_lib\lib\cdfml.jar;%mydir%\cdf_lib\lib\cdfjson.jar;%mydir%\cdf_lib\lib\cdfj.jar;%mydir%\cdf_lib\lib\gson-2.8.6.jar;%mydir%\cdf_lib\lib\javax.json-1.0.4.jar;.
      set PATH=%mydir%\cdf_lib;%mydir%\cdf_lib\bin;%PATH%
      set TERMINFO=%mydir%\cdf_lib\lib\terminfo
      set JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
      pytest --pyargs hermes_eea --cov hermes_eea
      env:
        PLATFORM: ${{ matrix.platform }}
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3

